---
#copyright: it is configured dynamically via hooks
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mvelikikh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mvelikikh/en
    - icon: material/email
      link: mailto:<my-github-username>@gmail.com
    - icon: material/rss
      link: /rss.xml
      name: RSS-лента заметок
extra_css:
  - assets/extra.css
hooks:
  - src/hooks.py
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets:
      base_path: !relative
      check_paths: true
  - pymdownx.superfences
  - toc:
      permalink: true
      permalink_title: Ссылка на этот заголовок
nav:
  - Заметки:
      - blog/index.md
      - tags.md
  - tools.md
not_in_nav: |
  /index.md
plugins:
  - blog:
      blog_toc: true
      categories: true
      categories_allowed:
        - Linux
        - Oracle
  - rss:
      categories:
        - categories
        - tags
      date_from_meta:
        as_creation: date.created
      feeds_filenames:
        rss_created: rss.xml
      match_path: blog/posts/.*
      use_git: false
  - search
  - tags:
      tags_allowed:
        # any version tag means that a post uses this version. It does not mean it applies exclusively to it
        - 9i
        - 11g
        # recognize 12.1 and 12.2 as the same version
        - 12c
        - 18c
        - 19c
        - 21c
        - 23ai
        - ASM
        # either a confirmed bug or very likely a bug
        - Bug
        - Clusterware
        # Oracle code symbols, e.g. C functions, variables
        - Code symbol
        - Data Guard
        # anytime set events/event is called or set
        - Diagnostic event
        # Edition-based redefinition
        - EBR
        # Applies to Oracle Engineered Systems in general, e.g. Exadata, ODA
        - Exadata
        - GoldenGate
        - Indexing
        - Initialization parameter
        - LOB
        # Oracle Enterprise Manager
        - OEM
        # Oracle errors, e.g. ORA-xxx, PRVG-xxx
        - OERR
        # any Oracle patching including OPatch/opatchauto
        - OPatch
        # Operating system related
        - OS
        - PL/SQL
        # Parallel execution
        - PX
        - Performance
        - RAC
        - RMAN
        - SQL
        - SQL*Plus
        - X$
repo_url: https://github.com/mvelikikh/mvelikikh.github.io
site_author: Великих М.А.
site_description: Oracle Database и сопутствующее, что я нашёл интересным
site_name: Путь базиста
site_url: https://mvelikikh.github.io
strict: true
theme:
  favicon: favicon.ico
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.select
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.integrate
  font:
    code: Roboto Mono
    text: Roboto
  language: ru
  logo: assets/database-search.png
  name: material
  palette:
    - accent: indigo
      primary: blue grey
      scheme: default
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - accent: indigo
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-7
        name: Светлая тема
validation:
  absolute_links: relative_to_docs
  anchors: warn
  omitted_files: warn
  unrecognized_links: warn
watch:
  - src
