---
name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install .
      - name: Build documentation
        run: python -m mkdocs build --strict
      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
